"""empty message

Revision ID: ec482f7c532b
Revises: c7f42ab44378
Create Date: 2023-03-19 21:13:17.724837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec482f7c532b'
down_revision = 'c7f42ab44378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('design_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('website_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('facebook_profile', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('instagram_profile', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['website_url'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('business_name')
        batch_op.drop_column('instagram_profile')
        batch_op.drop_column('facebook_profile')
        batch_op.drop_column('website_url')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.drop_table('post')
    op.drop_table('design')
    # ### end Alembic commands ###
